"""migration 4

Revision ID: e36e83059d0c
Revises: 054c68b67593
Create Date: 2024-09-25 15:40:30.608143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36e83059d0c'
down_revision: Union[str, None] = '054c68b67593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nft_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('listed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['nft_id'], ['nfts.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_listings_id'), 'sale_listings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_listings_id'), table_name='sale_listings')
    op.drop_table('sale_listings')
    # ### end Alembic commands ###
